# Generated by Django 5.1.3 on 2024-12-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forummessages',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forummessages',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_app.forummessages'),
        ),
        migrations.AddField(
            model_name='forummessages',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
